### ISSUE TITLE
XHR-Polling support?

### ISSUE THREAD

**Issue by miketucker** [NetEase/UnitySocketIO#1]
When running socket in long polling mode, eg:

  sio.configure(function() {
    sio.set("transports", ["xhr-polling"]);
    sio.set("polling duration", 10);
  });

I get the following socket debug message, and none of the messages are received by Unity:

   info  - handshake authorized WOsMURlFxbhuWDH0Ac0c
   warn  - unknown transport: "websocket"

Is this a matter of changing the UnitySocketIO settings, or is xhr-polling currently not supported?

**Comment by halfblood369** [comment]
Yea, the xhr-polling is currently not supported.
The project was initially designed for unity client of pomelo framework, so we have not test for xhr-polling.
