### ISSUE TITLE
On windows I can't connect to url with host names.

### ISSUE THREAD

**Issue by valyard** [NetEase/UnitySocketIO#12]
It seems that I can connect only to URLs containing IP addresses. It does handshaking successfully but after that just waits in "connecting" state forever.

For example if I try to connect ro 127.0.0.1:3700 it works, localhost:3700 doesn't.
Tried to connect to a remote server by host name — doesn't work.

Works fine on OS X.

**Comment by halfblood369** [comment]
Does your problem remain?

**Comment by valyard** [comment]
Yes. I dropped this project. There were to many problems using the library )8

**Comment by Kuirak** [comment]
Problem is still remaining - Could not connect to my node.js server until I found this Issue. If you need me to get any  data feel free to ask

**Comment by SagarDabas** [comment]
I also have the same problem. If anyone have been able to resolve it, please post the solution.
