### ISSUE TITLE
Callbacks cannot operate since not on  Main Thread

### ISSUE THREAD

**Issue by rojah** [NetEase/UnitySocketIO#17]
Good evening, I've tried to use the library and I am able to output the message and parse it but if I want to operate on GameObjects. Unity won't let me because the callback function is not operation from the main thread.
Has anyone found a solution?
Cheers,
Roger

**Comment by static-x** [comment]
You should operate in the Update() function. Here is a Javascript example:

var messages = ArrayList();

function GetMessageFromUnitySocketIO(msg:String) {  
  messages.Add(msg);
}

function Update () {  
    for (var msg: String in messages) {
        go.SendMessage(msg);
        messages.Remove(msg);
        return;
    }  
}
