### ISSUE TITLE
Source for SimpleJSON/ version number of SimpleJson being used 

### ISSUE THREAD

**Issue by neeravmehta** [NetEase/UnitySocketIO#2]
Hi, 
I have been looking for the source code of the SimlpeJSON.dll over the internet , but the project seems to have updated as the latest project on http://simplejson.codeplex.com/ has namespace as Simple.Json, where as the one that has been in this project has namespace SimpleJson.SimpleJson. 
Can you share the source of the dll that is used in this project ? 

Thanks 
Neerav
EDIT: I am new to GitHub , hence do not know how to post a question, please feel free to change it accodingly.

**Comment by halfblood369** [comment]
All of the dlls which are used in this project locate in file "UnitySocketIo/SocketIO/bin/Debug". You can find SimpleJson.dll.

**Comment by neeravmehta** [comment]
I know that the dll is in debug folder . I am looking for the source code of that dll.

**Comment by halfblood369** [comment]
Sorry, I do not have the source code of the SimpleJson.dll。
I did test on the latest project on http://simplejson.codeplex.com/ in pomelo-unitychat project just now, and it failed.
Because the latest project needs some DynamicObject which the unity does not support.

**Comment by neeravmehta** [comment]
Thanks for the update. in that case can you redirect me to some JSON parser that I can use in unity. The biggest problem I am facing with simpleJson is I am unable to debug any file that remotely touches SimpleJson. I have seen that the Unity Socket.Io is not very heavy dependent on simpleJson for parsing. Hence If I can swap the SimpleJson parts with some other parser which I can debug, it would make my life much easier.

**Comment by halfblood369** [comment]
I did not use other json parser in unity3d, may be you can achieve the json parser for unity3d just like https://github.com/felHR85/JsonSharp .
