### ISSUE TITLE
Not working with new socket.io 1.0.4 server

### ISSUE THREAD

**Issue by anhnt** [NetEase/UnitySocketIO#28]
Hi there,

I've been playing with new socket.io 1.0.4 server side, but the current UnitySocketIO client cannot connect. It did work properly with version 0.9 of socket.io server.

Please consider to upgrade UnitySocketIO client to compatible with new socket io 1.x.

Many thanks

**Comment by Avatarchik** [comment]
Hi,Will upgrade to this library (socket io 1.x)?

**Comment by anhnt** [comment]
No dude, still cannot connect to socket io 1.x server right now

**Comment by gtwind** [comment]
http://stackoverflow.com/questions/23946683/socket-io-bad-request-with-response-code0-messagetransport-unknown

**Comment by anhnt** [comment]
looks like this repo is no longer maintained. close this
