### ISSUE TITLE
Problems connecting to socket.io

### ISSUE THREAD

**Issue by philworthy** [NetEase/UnitySocketIO#3]
Hi. I'm writing a project in Unity4 and I'd love to use your great library to connect with a socket.io server but I'm running into some problems.

In Javascript I would usually write something like:

``` javascript
var socket = io.connect(url);
socket.emit(my_event, {my : 'data'} );
```

In C# (In Unity/MonoDevelop) I'm writing something like:

``` c#
socket = new Client(url);
socket.Connect();
socket.Send(???)
```

Problems:
1. I'm getting lots of non-descript errors in the console on connection even though it tells me it has connected (I'm doing a Console.log(e.Message))
   socket error: SocketIOClient.Messages.EventMessage
   socket opened
   socket error: SocketIOClient.Messages.ConnectMessage
   (note: this also seems to keep retrying in the background even after I stop running the Unity game, and sometimes ends in a freeze/crash)
2. I have no idea how to send the (my_event, {my : 'data'} ) combination to socket.io as the 'Send' method of the Client class only takes a single argument. Do I need to join the two arguments as a single piece of JSON somehow?

Thanks for any help you can share - it would be super appreciated!
(or any examples would be great?)

Thanks (and congratulations!)
Phil

**Comment by halfblood369** [comment]
There are two examples which can help you. pomelo-unityclient: https://github.com/NetEase/pomelo-unityclient , pomelo-unitychat: https://github.com/NetEase/pomelo-unitychat. 
1. Maybe you should list more error informations, such as where the error occurs……
2. The project was initially designed for unity client of pomelo framework. For pomelo, send function is enough and 
    I did not do lots of tests for other functions. Maybe you can have a try to use function emit.

**Comment by philworthy** [comment]
Thanks @halfblood369 .. 

I'll check out the two examples you sent, thanks. I had a brief look already actually but it looks very specific to pomelo not generic socket.io like I'm attempting. I can't understand why I'm getting errors - I've verified that the socket.io connection is working and sending data so this shoudl all be very basic.
1. I'm not really sure how to get more information on those. I'm quite new to Unity/C# so I'm still figuring it out but when I Console.log the e.Message I just get "SocketIOClient.Messages.ConnectMessage" or similar. It's happening in the Error event handler of my class. I tried re-writing my class in Unity Script to see if that would make any difference but it didn't :(
2. I didn't even see there was an Emit method in your Client class. Definitely I'll give that a try. Thanks! :)

For reference (incase I'm doing anything stupid) here's my code:

``` c#
using UnityEngine;
using System;
using System.Collections;
using SocketIOClient;

public class ListenOnSocketIO : MonoBehaviour {

    private Client socket = null; 

    void Start () {
        string socketUrl = "http://mysioserver";
        Debug.Log("socket url: "+socketUrl);

        this.socket = new Client(socketUrl);
        this.socket.Opened += this.SocketOpened;
        this.socket.Message += this.SocketMessage;
        this.socket.SocketConnectionClosed += this.SocketConnectionClosed;
        this.socket.Message += this.SocketError;
        this.socket.Connect();
    }

    private void SocketOpened (object sender, EventArgs e){
        Debug.Log("socket opened");
        this.socket.Emit("joinRoom", "1919119");
    }

    private void SocketMessage (object sender, MessageEventArgs e) {
        if ( e!= null && e.Message.Event == "message") {
            string msg = e.Message.MessageText;
            Debug.Log("socket message: " + msg);
        }
    }

    private void SocketConnectionClosed (object sender, EventArgs e) {
        Debug.Log("socket closed");
    }

    private void SocketError (object sender, MessageEventArgs e) {
        Debug.Log("socket error: " + e.Message);
    }
}
```

Thanks for your help!

**Comment by halfblood369** [comment]
In your Start function,"this.socket.Message += this.SocketError" is wrong. 

Please replace it with "this.socket.Error += this.SocketError"

**Comment by philworthy** [comment]
Thanks @halfblood369 , I corrected that mistake but still for some reason it doesn't work :(

Maybe if I explain some more what I'm trying to do...
I'm trying to connect to an event on livestream.com to get chat messages via the socket.io server.

I'm using this event to test with as it has fairly regular chat messages arriving on the socket.io (it's also easy enough to trigger the socket just by typing a message in the chat on the web page):
http://new.livestream.com/FosterKittenCam/TheCosmoFosters

Here is my javascript version (which is tested and works) with the full server URL and event ID on Livestream

``` javascript
var socket = io.connect("http://sio-1.new.livestream.com/events"); // connects me to the Livestream socket server
socket.emit("joinRoom", "1919119"); // joins the event so I can listen to chat from that event
```

And then I listen on "newComment" from socket.io, like this

``` javascript
socket.on("newComment", function (data) {
    console.log(data);
});
```

I know this might be a bit much to ask of you, but is there any possibility you would be able to test these URLs/events in your c# code just to tell me if there's anything I'm doing wrong. I really can't find my mistake :( 
(maybe it's something to do with socket.io versions?)

Thanks so much for your help! I really appreciate it!

**Comment by halfblood369** [comment]
As I mentioned above, The project was initially designed for unity client of pomelo framework. So I did not much of test for eventEmitter.
But I developed another eventManager based on this project, may be you can follow it. https://github.com/NetEase/pomelo-unityclient . The file EventManager may help you with eventEmitter.

**Comment by salsa2k** [comment]
Hi,

I'm trying to implements this... but im not receiving the opened log message

---

public Client socket = null; 

```
void Start () {
    string socketUrl = "http://myserver:7001";
    this.socket = new Client(socketUrl);
    this.socket.Opened += this.SocketOpened;
    this.socket.Message += this.SocketMessage;
    this.socket.SocketConnectionClosed += this.SocketConnectionClosed;
    this.socket.Error += this.SocketError;
    this.socket.Connect();
}

void SocketOpened(object sender, EventArgs e) {
    Debug.Log(e);
    Debug.Log("socket opened");
    this.socket.Emit("hello", "");
}
```

and when i go to my node console i can see the connection stabilished:

---

debug - client authorized
info  - handshake authorized CVe_t_6goZ9wr5Q3mnxn

---

do you know what can be?

Thanks :)

**Comment by halfblood369** [comment]
May be the information above can give you answer.

**Comment by awdng** [comment]
Did anyone resolve these issues ?
@halfblood369 
you are always referring to the pomelo EventManager which is fine, on the Unity side i can implement an EventManager to handle incoming messages, which come in fine.
But i cant figure out how to Emit an event on my nodejs based SocketIO Server...i tried emit() and send() sending  JSON or pure string but the event on the Server does not get called.

In your example your are using some custom protocol which isnt SocketIO specific so i cant see how that can be used to make this work. Any idea how to get events fired on the nodejs SocketIO server ?

i trief stuff like this.socket.Send("{\"name\": \"test\"}"); to no avail.
