### ISSUE TITLE
Unitysocketio在unity3d中需要使用多线程吗？

### ISSUE THREAD

**Issue by zhaoqingqing** [NetEase/UnitySocketIO#4]
服务器端使用Nodejs，前端使用unity3d，界面使用NGUI，通信用的unitysocketio,当我接收到服务器端返回的信息时，需要更新页面数据，但是报错了

TrySetSetString  can only be called from the main thread.
Constructors and field initializers will be executed from the loading thread when loading a scene.
Don't use this function in the constructor or field initializers, instead move initialization code to the Awake or Start function.

向大家请教如何处理这个问题，是否是线程的问题还是其它的？

**Comment by halfblood369** [comment]
在Unity里面，初始化的工作需要移到Awake或者Start里面，播放动画帧是在OnGUI函数里面的。
你把更新页面数据的代码发上来看看……

**Comment by zhaoqingqing** [comment]
现在这三天放假，等后天去公司后把更新页面数据的代码贴上来，我前天在进行打包的时候，还发现一个问题，就是我打成apk和exe之后，socketio连接不上，没有建立与服务器的连接，还有我打成html的时候，会报错，具体错误信息，后天我去公司后再把它贴出来，不知道你们是否有遇到过打包后socketio不起作用的问题？

**Comment by halfblood369** [comment]
https://github.com/NetEase/pomelo-cn/issues/168
