### ISSUE TITLE
使用UnitySocketio打包后连接不上服务器，pomelo-unitychat可以聊天

### ISSUE THREAD

**Issue by zhaoqingqing** [NetEase/UnitySocketIO#5]
客户端使用的是UnitySocketio与服务器进行通信，与pomelo-unitychat (https://github.com/NetEase/pomelo-unitychat) 一样是基于U3D与NodeJS的项目。
但是服务器端没有用Pomelo,只是单纯的Nodejs，客户端使用UnistySocketIO。
在Unity中开发是能够正常与服务器连接，接收数据，但是打包之后就连接不上服务器。打包成什么格式都不能连接服务器。经过几次尝试之后，我很认真地参考了pomelo-unitychat，就是socket那部分，pomelo-unitychat使用PomeloClient，我的项目使用的是UnitySocketIO。
我把pomelo-unitychat运行起来的效果如下：
![chat ](https://f.cloud.github.com/assets/3056814/396246/06f1a1f4-a81c-11e2-8074-7fb547bf716d.png)
我做了一个测试Demo和我的项目写法是一样的，地址如下：
百度网盘：
只有源码：http://pan.baidu.com/share/link?shareid=473125&uk=1276168936
带打包文件：http://pan.baidu.com/share/link?shareid=473126&uk=1276168936
新浪V盘：
http://vdisk.weibo.com/s/y4_1P

**Comment by halfblood369** [comment]
把Connect方法放到初始化函数Start里面……

**Comment by zhaoqingqing** [comment]
![connCode](https://f.cloud.github.com/assets/3056814/396470/0d3dc20e-a826-11e2-8bfa-c22b8fcfb3d1.png)
![connectionError](https://f.cloud.github.com/assets/3056814/396471/1e760d6a-a826-11e2-8975-575e018926c9.png)

**Comment by zhaoqingqing** [comment]
我把连接代码放在Start里面，打包之后还是不能成功与服务器建立连接

**Comment by zhaoqingqing** [comment]
你那里放在Start里面打包之后可以运行么？

**Comment by zhaoqingqing** [comment]
![devOK](https://f.cloud.github.com/assets/3056814/396480/8c961c72-a826-11e2-8fde-232cea702fbb.png)

**Comment by zhaoqingqing** [comment]
在Unity开发工具中是可以与服务器建立连接的，求解，大神

**Comment by halfblood369** [comment]
放在start里面可以连接，服务器显示连接上了！

**Comment by zhaoqingqing** [comment]
但是我的OnGUI里面显示不出来接收到服务器返回的数据，求解，那句“ GUILayout.Label("打包之后与服务器连接失败"); ”是在接收服务器数据长度为O时显示在界面上的。
如果连接上了的话，那应该是和在Unity里面显示一样的吧？
可是显示出来的是服务器返回长度0，没有接收到数据

**Comment by zhaoqingqing** [comment]
如果服务器那边连接上了，服务器会返回当前在线人数给客户端，然后我在OnGUI()函数里面用 
 GUILayout.Label("服务器返回数据：" + receiveMSG);
把服务器返回的数据显示出来

**Comment by halfblood369** [comment]
已解决，请重新下载SocketIO.dll……
