### ISSUE TITLE
Don't work

### ISSUE THREAD

**Issue by flashhawk** [NetEase/UnitySocketIO#7]
/// <summary>

        /// <para>Asynchronously calls the action delegate on event message notification</para>
        /// <para>Mimicks the Socket.IO client 'socket.on('name',function(data){});' pattern</para>
        /// <para>Reserved socket.io event names available: connect, disconnect, open, close, error, retry, reconnect  </para>
        /// </summary>

        /// <param name="eventName"></param>
        /// <param name="action"></param>
        /// <example>
        /// client.On("testme", (data) =>
        ///    {
        ///        Debug.WriteLine(data.ToJson());
        ///    });
        /// </example>
        public virtual void On(
            string eventName,
            Action<IMessage> action)
        {
            this.registrationManager.AddOnEvent(eventName, action);
        }

**Comment by halfblood369** [comment]
The project was initially designed for unity client of pomelo framework. For pomelo, the event handler is unuseful, so the functions 'emit' and 'on' is not test. May you can use function of client.send(msg) and develop your event handler  such as pomeloclient: https://github.com/NetEase/pomelo-unityclient/blob/master/pomelo-unityclient/pomelo-unityclient/EventManager.cs .

**Comment by flashhawk** [comment]
Thanks a lot!
